//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManageJob
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ManageJob()
        {
            this.jobseeks = new HashSet<jobseek>();
        }
    
        public int JobId { get; set; }
        public string JobName { get; set; }
        public string JobSkills { get; set; }
        public string JobExpirience { get; set; }
        public Nullable<bool> JobIsActive { get; set; }
        public string JobDocuments { get; set; }
        public string JobCreatedBy { get; set; }
        public string JobModifiedBy { get; set; }
        public Nullable<System.DateTime> JobCreatedDate { get; set; }
        public Nullable<System.DateTime> JobModifiedDate { get; set; }
        public Nullable<int> RefDepartmentId { get; set; }
        public Nullable<int> RefCityId { get; set; }
    
        public virtual CityMaster CityMaster { get; set; }
        public virtual Department Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<jobseek> jobseeks { get; set; }
    }
}
