//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobPortal.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class UserMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserMaster()
        {
            this.jobseeks = new HashSet<jobseek>();
        }
    
        public int UserId { get; set; }
        
        [Required]
        public string UserName { get; set; }
        [Required]
        public string UserPassword { get; set; }
        [Required]
        public string UserAddress1 { get; set; }
        public string UserAddress2 { get; set; }
        [Required]
        public string UserGender { get; set; }
        public Nullable<System.DateTime> UserDOB { get; set; }
        public Nullable<int> UserContact { get; set; }
        public string UserEmail { get; set; }
        public string UserSkills { get; set; }
        public Nullable<decimal> UserExperience { get; set; }
        [Required]
        public string UserDoc { get; set; }
        public string UCreatedBy { get; set; }
        public string UModifiedBy { get; set; }
        public Nullable<System.DateTime> UCreatedDate { get; set; }
        public Nullable<System.DateTime> UModifiedDate { get; set; }
       
        public Nullable<int> RefDepartmentId { get; set; }
       
        public Nullable<int> RefCityId { get; set; }
    
        public virtual CityMaster CityMaster { get; set; }
        public virtual Department Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<jobseek> jobseeks { get; set; }
    }
}
